### ISSUE TITLE
Refined Sections

### ISSUE THREAD

**Issue by nuclearsugar** [making360/making360#158]
Hey guys! The book is quite an amazing read. You should be proud. 

In writing an intro chapter, I had a crazy idea that hopefully isn’t a major headache… I thought that the two main sections of the book could be split into more refined sections. I realize this may be too big of an idea, especially just a few days prior to publishing, but I think it may help to streamline all of your hard work and enhance reader comprehension. But with all honesty, please feel free to throw out this idea.

=== EQUIP
Elements
Platonic Rigs
Play Your Cards Right

=== SETUP
Formatting Cards
World Clock
Set and Settings
Get Juiced
Lifetime Supply
Pair to Remote
Multiple Rigs
Realtime Preview

=== PLAN
Safety Zones
Sandbag
Shoot the Moon
Hide and Seek!

=== SHOOT
Reference Signals
Hit and Run!
Flashing Lights
Stabilization
Lighting
Misfires
Ring Around the Rosey
Beep Code
Frozen
On Fire
Modified Fisheye

=== IMPORT
Dymaxion Chronofile
Ingestion

=== STITCH
Dailies Quickstitch
First Assembly
Color Matching
Synchronization
Background vs Foreground
Optimization Settings
Control Points
Parallax between Cameras
One Seam Leads to Another
Surreal Bodies
Template Stitch
Masking Points
Stereoscopic 3D 360
Circular Crop Factor
First Person
Moving Shots
A/B Testing
Patching Nadir
Stitch Anything
Stitch to Defish
Noisy Footage

=== EDIT
Mise en Place
Rotoscoping
AE Comping
Chroma Keying
Color Grading
Hello FFmpeg
Almost Done!

**Comment by vickixhuang** [comment]
we're live!! yay! just send out an update to our kickstarter backers only. so they now have the public github link and pdf link. we're going to add the sections in tomorrow so the book will have the sub-categories you suggested color coded. thanks! we'll replace the sectionized pdf too, we promised the backers something dec 1 =P. 
thanks soo much for your work @nuclearsugar @AndrewHazelden!!! really excited to see how it is received and hopefully travels word of mouth. we'll see the feedback we get and update before the official jan 1 public release.

**Comment by AndrewHazelden** [comment]
A big round of congratulations to @vickixhuang and @fsoudiere ! You two have spearheaded the publication of this exciting new 360&deg; film production guide book and your determination has brought it into existence. :-) I really like @nuclearsugar 's introduction text and I'm happy that I could help out even just a little bit on the final delivery phase.

**Comment by AndrewHazelden** [comment]
I noticed the new release entry on GitHub. You should edit the release entry details and then manually attach the PDF file to that release in the drag and drop field. 

That way people have the option to directly click "download" right on the PDF file directly without needing to get all of the raw LaTex files and other resources which come in the ZIP download option on the specific release. 

The URL for editing this release page is: https://github.com/making360/making360/releases/edit/1.0.0

![releases page editing](https://cloud.githubusercontent.com/assets/909728/11512568/1cc4d660-9845-11e5-8093-5010b70d141d.png)

**Comment by vickixhuang** [comment]
oo thanks! just updated it that's convenient, some people probably shy away when they see "Source Code" haha

**Comment by nuclearsugar** [comment]
Yehaw! Congrats everyone. Don't forget to take a moment and celebrate.

**Comment by nuclearsugar** [comment]
Also I added links to the release on my two relevant blog posts:
http://thefulldomeblog.com/2014/03/06/360-video-fundamentals/
http://thefulldomeblog.com/2015/11/17/collection-of-360-video-rigs/

**Comment by fsoudiere** [comment]
you're so super duper nice thank you Jason!!!

**Comment by fsoudiere** [comment]
@AndrewHazelden @nuclearsugar @vickixhuang Can I get a quick OK to print for you guys? I reorganized and colorized our refined sections by Jason Fletcher!! Looks more colorful and organized but i want to make sure all edits are good to go for first print order.

thanks

**Comment by nuclearsugar** [comment]
I can see you guys have been working hard on this. Looks really great and makes the book quite solid. I bet you're excited to print.

The only thing that stands out to me is that some of the section colors are very similar. Here is a quick sketch of a possible change.
![section-colors](https://cloud.githubusercontent.com/assets/8218211/11552135/fccd3b62-994e-11e5-8ed1-6417b4cf3c47.jpg)

**Comment by nuclearsugar** [comment]
Perhaps making the section color a bit deeper green too.

**Comment by nuclearsugar** [comment]
Also there are page numbers visible on the section dividers (equip, setup, plan, shoot). But they have already been removed from the Problems of Stitching sections.

**Comment by nuclearsugar** [comment]
And one last suggestion. Add one more page to the very end, saying something to the effect of: 

Now put down this book and go shoot some 360 video!

Have a tip that isn't already in this book? Contribute to this open-source project.
making360.com

**Comment by fsoudiere** [comment]
@nuclearsugar working on it

**Comment by nuclearsugar** [comment]
Page 12: The quote by Gene Youngblood feels a bit out of place being at the end of a chapter. Perhaps something to cut?

Page 72: With a little bit of editing, this chapter can fit onto one page. See below:

BEFORE:
```
\clearpage
\solution
{\large Get a journal or notebook to keep track of production notes, takes, the month and date of each new morning, and share your growth! \par}
```

AFTER
```
\solution
{\large Get a journal or notebook to keep track of production notes, takes, and the date.\par}
```

**Comment by vickixhuang** [comment]
for some reason the link in world clock came out as 
The Time/Date can be used as a form of metadata for reference during the textbfIngestion and stitching process later on.

**Comment by AndrewHazelden** [comment]
Hi. I just scrolled through the PDF file this morning with the newly updated table of contents and it looks good to me. The colorized chapter sections look really nice and the little bar of color on each chapter heading throughout the book is quite classy too. Good Work! :-)

**Comment by vickixhuang** [comment]
thanks @AndrewHazelden!! and @nuclearsugar for the last minute revisions!! good call on the last page =) the books are ordered yeee! we'll let you know when they come in.

**Comment by nuclearsugar** [comment]
Hurrah! Milestone reached! Nice job guys.
