### ISSUE TITLE
a/b testing on Gear VR using streaming

### ISSUE THREAD

**Issue by neuhaus** [making360/making360#200]
The A/B testing chapter currently suggests using SmartSwitch for uploading files to a Samsung device.

There is another option:

You can **stream** your own videos to your Gear VR running Milk VR.
There are two free tools that can help you with that:
* https://github.com/abnormalend/milkvr-url-maker and
* https://github.com/heavykick/MilkVRLauncher

You will need to run a HTTP server on your computer to serve the movie files, but no more copying!

I'd make a pull request for you, but I don't know LaTeX, sorry.

PS: Milk VR is only available in the US at the moment, so if you're outside the US, get a US VPN connection for your Samsung device and install it (US VPN is only required during installation).

**Comment by fsoudiere** [comment]
Hey @neuhaus, that's some great stuff to add to the book. Could you add a small paragraph maybe? Just follow this quick tut i did to do a pull request without knowing Latex: https://www.youtube.com/watch?v=-sD3Nr-St4g&feature=youtu.be

**Comment by neuhaus** [comment]
OK, I gave it a shot...

**Comment by fsoudiere** [comment]
thank you @neuhaus!
