### ISSUE TITLE
spanish translation

### ISSUE THREAD

**Issue by fsoudiere** [making360/making360#209]
Nilo Enrique Canales Bernales will be in charged of that.

**Comment by miguelbandera** [comment]
I can help in the spanish translation

**Comment by fsoudiere** [comment]
thank you @miguelbandera, cc @bangteufel you guys will rock that translation!!!

**Comment by bangteufel** [comment]
Muy bien @miguelbandera nos organizamos para hacerlo. Thank you @fsoudiere for your support!

**Comment by fsoudiere** [comment]
Hey @bangteufel, just wondering how you doing with the translation? if the undertaking is too much we could help you maybe outreach to get more friends to help translate making360 to spanish.

**Comment by juangz26** [comment]
Hello all! I'm a native Spanish speaker, I could gladly help you out with this translation :) Who should I contact?

**Comment by bangteufel** [comment]
Hello @juangz26 Write me an email. nilo.canales@gmail.com I'm at the page 60, I'll be happy to receive your support as long as you have free time.

**Comment by bangteufel** [comment]
Thank you for write me an email @juangz26. We will be in contact in a week. :)

**Comment by sergiobd** [comment]
I'm in for spanish translation if you still need help!

**Comment by bangteufel** [comment]
Hello everybody, work done. Hola a todos, trabajo terminado. Pronto estaremos cargando la traducción total del libro making360 Gracias @fsoudiere
