### ISSUE TITLE
Access Denied on most footage

### ISSUE THREAD

**Issue by e1e8** [making360/making360#218]
Only the first two chapXX.zip files resolve via AWS. (chap34, chap30)
(Dailies Quickstitch and Background vs Foreground)

All others are getting Access Denied error.
Chapters with this error:
Control Points
Parallax between Cameras
One Seam Leads to Another
Surreal Bodies
Template Stitch
Moving Shots
Patching Nadir
Stitch Anything
Stitch to Defish
Noisy Footage

**Comment by fsoudiere** [comment]
I think the links were not public and now they are. Sorry about this! Have fun stitching!
